//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.11.0
//     from Assets/Controls/PlayerControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerControls: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerControls"",
    ""maps"": [
        {
            ""name"": ""Player"",
            ""id"": ""ff5a7c2d-1673-4ce8-b028-73cd17c4c1f7"",
            ""actions"": [
                {
                    ""name"": ""FingerLeft"",
                    ""type"": ""Button"",
                    ""id"": ""23ca8a23-c3f2-4108-b862-ab74ec3a7b26"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""FingerRight"",
                    ""type"": ""Button"",
                    ""id"": ""4905f20d-9850-4556-bdbb-459c86a23920"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Pause"",
                    ""type"": ""Button"",
                    ""id"": ""b848d38f-42b4-4cd7-96c6-96db386dd32a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Cancel"",
                    ""type"": ""Button"",
                    ""id"": ""4a146562-77fe-4804-9d9e-9ad294970083"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SelectFinger"",
                    ""type"": ""Button"",
                    ""id"": ""a19647d5-ad39-46ae-8644-3c2b6f22e7f5"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""DebugHandSwap"",
                    ""type"": ""PassThrough"",
                    ""id"": ""941744c0-fa64-47b3-9a45-5e8713eb7747"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PlayCards"",
                    ""type"": ""Button"",
                    ""id"": ""d641cd7f-3913-4e2e-8355-b78b750ebfc5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""13f40110-da8d-4d85-b413-a2813252d66c"",
                    ""path"": ""<Gamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cbcd22b9-3a5e-4b7a-a58e-3c1324bada0e"",
                    ""path"": ""<Keyboard>/backspace"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""69db217e-a6d4-4db1-b387-a78d7b9f46e3"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Cancel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0ebe438a-0731-4607-95ac-ff4c7c4cecaf"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""SelectFinger"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""92d95cfd-2143-4be8-ac4f-15282a4bb032"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectFinger"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""30d75d9d-89bc-4e03-a9ee-b940b71e2b38"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DebugHandSwap"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""482fda32-3950-4a72-a005-8ddff100507f"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""FingerLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""65a29646-c2a4-486b-973c-dfb96157356c"",
                    ""path"": ""<Gamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""FingerLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""22a7ab3e-8876-49bd-bd89-a376371c6008"",
                    ""path"": ""<Gamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""FingerLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""dbe550bb-7ba4-470e-8a93-c1c140f8b8aa"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""FingerRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a8af2a34-0581-4239-ba56-8b0694dc3d2d"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""FingerRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5d0cc5bf-1c47-4be8-92f8-632e01b19e1b"",
                    ""path"": ""<Gamepad>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""FingerRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9fdb1ea9-04b3-4dad-ab21-bba2dc15c2a2"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""PlayCards"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""UI"",
            ""id"": ""2ae069f1-6793-41d6-82fe-4dec30dfc3b5"",
            ""actions"": [
                {
                    ""name"": ""UI_Move"",
                    ""type"": ""PassThrough"",
                    ""id"": ""627ad011-9d32-454c-933f-afb2b9b824a5"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""UI_Select"",
                    ""type"": ""Button"",
                    ""id"": ""97c9da3b-aa1e-43bb-adec-7c66f7c4264f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""Dpad"",
                    ""id"": ""4782503e-3ec7-4437-bda6-1125350c6834"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UI_Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""019c3218-ecd5-462b-94ed-f0ac77334b5b"",
                    ""path"": ""<Gamepad>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""UI_Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""b6a1693e-c79d-409c-be48-0a8da4ff3711"",
                    ""path"": ""<Gamepad>/dpad/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""UI_Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""b66ea053-1ab7-4caf-8ed1-4c144c5cb640"",
                    ""path"": ""<Gamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""UI_Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""b69d7ced-51d9-4e20-a45f-e9f7380f1bfe"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""UI_Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""LeftJoystick"",
                    ""id"": ""ff786e47-9728-4dc6-a45b-9abd62aab166"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UI_Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""e82b3940-cf62-48a6-9f43-f9d7799a982b"",
                    ""path"": ""<Gamepad>/leftStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""UI_Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""434b660d-e841-41b2-9e3c-f73de3adaadb"",
                    ""path"": ""<Gamepad>/leftStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""UI_Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""f7da9f91-1b72-4ba2-8550-534fc0fce7fb"",
                    ""path"": ""<Gamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""UI_Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""9dcd3d3e-e34d-4bfd-8bbe-7b15b99421c2"",
                    ""path"": ""<Gamepad>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""UI_Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Keyboard"",
                    ""id"": ""6c3c8306-87f6-4f95-9b36-47242c0e098b"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UI_Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""0a25fcd8-16f3-425d-aed1-3c3223b2ec9b"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""UI_Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""204e95f7-f064-4f0f-ad8d-6f927651869f"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""UI_Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""163bb74d-9581-4e51-9e31-d5202ddd8cca"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""UI_Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""95714239-2807-401e-bcd0-407468df0435"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""UI_Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""7d1074ec-27d6-4423-a530-1603f349fe31"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UI_Select"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c2ece352-1d7d-448c-a464-101e2b41a0f1"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UI_Select"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""QTE"",
            ""id"": ""4475d2fe-57ba-4a60-9c4c-15aa55c556d8"",
            ""actions"": [
                {
                    ""name"": ""North"",
                    ""type"": ""PassThrough"",
                    ""id"": ""65dddba1-7d64-4b46-957f-f675994d211e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""South"",
                    ""type"": ""PassThrough"",
                    ""id"": ""15509ad1-4c26-4a45-b324-2a3c8cf7a09f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""East"",
                    ""type"": ""PassThrough"",
                    ""id"": ""5311653b-c272-4ecb-8831-160984249618"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""West"",
                    ""type"": ""PassThrough"",
                    ""id"": ""bcc7165a-27b9-4aed-9827-321e3a227816"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""DPadUp"",
                    ""type"": ""PassThrough"",
                    ""id"": ""d966bf5a-a3b9-4bc3-ad0a-99814ce473b4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""DPadDown"",
                    ""type"": ""PassThrough"",
                    ""id"": ""baa302ea-41d5-4bdd-8943-77cd8fc0bab7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""DPadLeft"",
                    ""type"": ""PassThrough"",
                    ""id"": ""51d78d06-fb10-4ded-a7e7-b6f0872ca7c2"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""DPadRight"",
                    ""type"": ""PassThrough"",
                    ""id"": ""681f615c-707b-4d9c-9dd2-8e3713adcc14"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""LS Up"",
                    ""type"": ""Button"",
                    ""id"": ""28850366-06ae-424d-be52-bd7c6619a331"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LS Down"",
                    ""type"": ""Button"",
                    ""id"": ""583d444f-8d27-488c-a2b8-cf92cbaae065"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LS Left"",
                    ""type"": ""Button"",
                    ""id"": ""089a447b-21f1-4b97-b8e5-e01d3d7f906d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LS Right"",
                    ""type"": ""Button"",
                    ""id"": ""344efd4d-ada1-4678-a5e4-35c80558e495"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RS Up"",
                    ""type"": ""Button"",
                    ""id"": ""662b93b7-4733-428e-9f77-1ff8762f8b00"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RS Down"",
                    ""type"": ""Button"",
                    ""id"": ""c8810a08-09c0-4fb4-a08b-55240ba60647"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RS Left"",
                    ""type"": ""Button"",
                    ""id"": ""ae2fecc9-beac-4084-87bf-d72273093a40"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RS Right"",
                    ""type"": ""Button"",
                    ""id"": ""0eca3d8a-bf48-4c12-a47a-2793ada81bd8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RB"",
                    ""type"": ""Button"",
                    ""id"": ""224f4ea7-fab6-4f55-ba91-6a5a2f0403ca"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LB"",
                    ""type"": ""Button"",
                    ""id"": ""88329351-71cb-4a79-bd2f-9846fc949b26"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RT"",
                    ""type"": ""Button"",
                    ""id"": ""3e641c5e-ee6e-4f95-a0ca-3ea7413fe41e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LT"",
                    ""type"": ""Button"",
                    ""id"": ""3d0b37da-9f7f-42f2-91d2-8a4201966e59"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""DebugTriggerQTE"",
                    ""type"": ""PassThrough"",
                    ""id"": ""7f5426c0-3314-474a-bb24-d8a224e2c09a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Pause"",
                    ""type"": ""PassThrough"",
                    ""id"": ""96ed138b-15d3-47b7-a236-71cefc7a2ced"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""25b4ce89-5a22-4727-8bf4-42a0c29abfb1"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""South"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""406d67ee-be46-42d3-9e78-3f6dc2e5b402"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""South"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""18eb3166-49b6-4641-bc47-ffffcc9adb07"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""North"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""67b4950c-9e5d-4e91-83cc-4ee2ceeec136"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""North"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""dd3d728a-c353-4839-ba2f-f87fcf8adb92"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""East"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f883c4c6-908b-4047-9511-d893c34560a1"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""East"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8619d141-d0d0-4a81-8862-ddeaa2abc735"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""West"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""decb5244-95e3-4c16-a59e-9695d44158df"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""West"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8002b9bb-a438-4fcb-a2cb-dd0271c5db5c"",
                    ""path"": ""<Gamepad>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""DPadUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""868b0471-1cd0-4e6e-a431-58c130f096ef"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""DPadUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1db3b615-5e14-4143-9415-30177e4910e7"",
                    ""path"": ""<Gamepad>/leftStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""DPadUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0b0d41c7-e2cb-4871-b53c-c4d7a0f4e65a"",
                    ""path"": ""<Gamepad>/dpad/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""DPadDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""838ce385-7e84-4459-a25c-51d698a7c72f"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DPadDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1243b5fb-87b6-42a0-94cd-b8df361e13e0"",
                    ""path"": ""<Gamepad>/leftStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""DPadDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d4cb1fb2-92b6-4583-8548-b4bd8b5c2f79"",
                    ""path"": ""<Gamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""DPadLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5f4eba23-bf72-4791-89f0-4ff3390259c9"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DPadLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""dac8637e-b6f9-4371-b34f-f3e0c3d20490"",
                    ""path"": ""<Gamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""DPadLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""57ec50e8-d1d7-4f2d-a8cd-491bc7caf9fe"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""DPadRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b62604f3-5776-4cff-9a93-0ccb9c17dc8a"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DPadRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""26e65ab4-5a51-489a-bdb8-e46c171a1d9d"",
                    ""path"": ""<Gamepad>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""DPadRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f1964073-8279-4ff4-8308-8d5542773985"",
                    ""path"": ""<Gamepad>/leftStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""LS Up"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b0024f8e-00c7-4dda-801c-2d4e7f5493b9"",
                    ""path"": ""<Gamepad>/leftStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""LS Down"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""29a6069d-1e82-4162-a60e-7b4b728835a5"",
                    ""path"": ""<Gamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""LS Left"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5784cd49-9233-46a5-852b-ba4fa39ad09a"",
                    ""path"": ""<Gamepad>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""LS Right"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c467c651-1a3d-4d30-91f1-208d8fa07588"",
                    ""path"": ""<Gamepad>/rightStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""RS Up"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""995fb6f4-ddf7-41ea-b62f-78864bcca767"",
                    ""path"": ""<Gamepad>/rightStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""RS Down"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""78037597-8980-4f88-a2ae-3428b4435a7d"",
                    ""path"": ""<Gamepad>/rightStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""RS Left"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""76820899-de79-4861-bb7a-8530c386bda4"",
                    ""path"": ""<Gamepad>/rightStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""RS Right"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""58bd1502-6d1f-49cf-bf5a-97b415407264"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""RB"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""25d30902-e476-4bac-b011-dd9d6a88c77f"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""LB"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7676c0c3-8548-4060-a01c-8ee977314fbe"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""RT"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b3617bc8-41f8-45ef-8fb7-a30b791a0e81"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""LT"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""80d05058-9068-4f6a-a393-11fd4c5f830a"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""DebugTriggerQTE"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""640996d5-e294-4ba5-9bb2-7808a95e408c"",
                    ""path"": ""<Gamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""655bd5ab-63c9-4406-b521-18d5507e6fc7"",
                    ""path"": ""<Keyboard>/backspace"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Card"",
            ""id"": ""57d2df53-2581-4f41-a44d-603402ed5ebc"",
            ""actions"": [
                {
                    ""name"": ""Deselect"",
                    ""type"": ""Button"",
                    ""id"": ""b6ce535f-4e61-4efe-8601-07b3beb25429"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Select"",
                    ""type"": ""Button"",
                    ""id"": ""e9f11fe7-7bb9-4885-b8e2-1c896be1f815"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""NavCardLeft"",
                    ""type"": ""Button"",
                    ""id"": ""ee8fbd1e-e676-4acc-8fbc-f357059195de"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""NavCardRight"",
                    ""type"": ""Button"",
                    ""id"": ""1c414d8d-cd80-4686-9f3f-ed973d994587"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""CameraUp"",
                    ""type"": ""PassThrough"",
                    ""id"": ""ee3ca8fe-005d-4874-bc80-e9bf3e914fc2"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""CameraDown"",
                    ""type"": ""PassThrough"",
                    ""id"": ""1274b357-e977-45d0-b321-2c67ffbd2da0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""SetFinal"",
                    ""type"": ""PassThrough"",
                    ""id"": ""fb9f5e7c-dcac-49aa-9bc0-8feed6a5d567"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Pause"",
                    ""type"": ""PassThrough"",
                    ""id"": ""5dceca5b-dfa1-4d6f-9ecc-5122f279db73"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ManaView"",
                    ""type"": ""Button"",
                    ""id"": ""ff56b4d9-a07b-4978-92dc-61e0ebf36589"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""5f3f031b-5959-441b-a187-2a834831aaa6"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""NavCardLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a62e7000-c33b-422c-be23-b0089e916811"",
                    ""path"": ""<Gamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""NavCardLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""151991c5-c2b3-40c5-b31e-2a3057b71551"",
                    ""path"": ""<Gamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""NavCardLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5964c6bd-782e-40c8-a6b4-a947ed50ba51"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""NavCardRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ab65f47e-811b-41aa-8564-e3de1e733460"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""NavCardRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0bf16dec-c9ab-4bd6-bff2-458c9ebbf07e"",
                    ""path"": ""<Gamepad>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""NavCardRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""916c67f3-d353-4797-bc39-a7000b3471df"",
                    ""path"": ""<Gamepad>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""CameraUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f25f1b1d-698e-47ef-adf4-90f0cc6b6cdb"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""CameraUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2fb4eec6-243f-4436-92fe-68e77ab25dca"",
                    ""path"": ""<Gamepad>/leftStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""CameraUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""eac53a52-5c95-464c-9679-a78cbe16e9eb"",
                    ""path"": ""<Gamepad>/dpad/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""CameraDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5b99d9a7-ab72-4b38-a8ec-69aec31c041c"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""CameraDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bc18a8b7-a21e-4c41-be93-0e165c2cf01b"",
                    ""path"": ""<Gamepad>/leftStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""CameraDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9592d9ca-c6a6-45a4-bb21-341511a18ecf"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Select"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2929a0f4-9ded-4c5e-969b-a290abacbe86"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Select"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4d16f49e-84c7-4f05-82dd-f992a3511281"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Deselect"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""02814ff1-58ed-40a3-8dac-9ab60599a1df"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""SetFinal"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4121e832-a3c4-4443-a9b0-e3c8800ffc30"",
                    ""path"": ""<Gamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""384c35e1-cf0f-4e2c-9841-2ccb7cf62a57"",
                    ""path"": ""<Keyboard>/backspace"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""552b0150-c6d3-43bc-a382-88ab1836acf9"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""ManaView"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""QTEWait"",
            ""id"": ""440db8c3-821a-4318-bfd1-b5c7b0828132"",
            ""actions"": [
                {
                    ""name"": ""Pause"",
                    ""type"": ""PassThrough"",
                    ""id"": ""62dd92e4-24bf-42d8-aa4b-83422cda8451"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""UnConfirm"",
                    ""type"": ""Button"",
                    ""id"": ""1fd75cb9-d73a-40d9-8db7-1291825a5ab0"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""f08eaeb7-66e2-4489-8ec1-aa4f992b8059"",
                    ""path"": ""<Gamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c67661b4-8280-4ce9-a373-09888ee59f5a"",
                    ""path"": ""<Keyboard>/backspace"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""210fbfb1-0860-4a11-8dc3-3e40bdc52884"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Gamepad"",
                    ""action"": ""UnConfirm"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Keyboard&Mouse"",
            ""bindingGroup"": ""Keyboard&Mouse"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<Mouse>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""Gamepad"",
            ""bindingGroup"": ""Gamepad"",
            ""devices"": [
                {
                    ""devicePath"": ""<Gamepad>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""Touch"",
            ""bindingGroup"": ""Touch"",
            ""devices"": [
                {
                    ""devicePath"": ""<Touchscreen>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""Joystick"",
            ""bindingGroup"": ""Joystick"",
            ""devices"": [
                {
                    ""devicePath"": ""<Joystick>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""XR"",
            ""bindingGroup"": ""XR"",
            ""devices"": [
                {
                    ""devicePath"": ""<XRController>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // Player
        m_Player = asset.FindActionMap("Player", throwIfNotFound: true);
        m_Player_FingerLeft = m_Player.FindAction("FingerLeft", throwIfNotFound: true);
        m_Player_FingerRight = m_Player.FindAction("FingerRight", throwIfNotFound: true);
        m_Player_Pause = m_Player.FindAction("Pause", throwIfNotFound: true);
        m_Player_Cancel = m_Player.FindAction("Cancel", throwIfNotFound: true);
        m_Player_SelectFinger = m_Player.FindAction("SelectFinger", throwIfNotFound: true);
        m_Player_DebugHandSwap = m_Player.FindAction("DebugHandSwap", throwIfNotFound: true);
        m_Player_PlayCards = m_Player.FindAction("PlayCards", throwIfNotFound: true);
        // UI
        m_UI = asset.FindActionMap("UI", throwIfNotFound: true);
        m_UI_UI_Move = m_UI.FindAction("UI_Move", throwIfNotFound: true);
        m_UI_UI_Select = m_UI.FindAction("UI_Select", throwIfNotFound: true);
        // QTE
        m_QTE = asset.FindActionMap("QTE", throwIfNotFound: true);
        m_QTE_North = m_QTE.FindAction("North", throwIfNotFound: true);
        m_QTE_South = m_QTE.FindAction("South", throwIfNotFound: true);
        m_QTE_East = m_QTE.FindAction("East", throwIfNotFound: true);
        m_QTE_West = m_QTE.FindAction("West", throwIfNotFound: true);
        m_QTE_DPadUp = m_QTE.FindAction("DPadUp", throwIfNotFound: true);
        m_QTE_DPadDown = m_QTE.FindAction("DPadDown", throwIfNotFound: true);
        m_QTE_DPadLeft = m_QTE.FindAction("DPadLeft", throwIfNotFound: true);
        m_QTE_DPadRight = m_QTE.FindAction("DPadRight", throwIfNotFound: true);
        m_QTE_LSUp = m_QTE.FindAction("LS Up", throwIfNotFound: true);
        m_QTE_LSDown = m_QTE.FindAction("LS Down", throwIfNotFound: true);
        m_QTE_LSLeft = m_QTE.FindAction("LS Left", throwIfNotFound: true);
        m_QTE_LSRight = m_QTE.FindAction("LS Right", throwIfNotFound: true);
        m_QTE_RSUp = m_QTE.FindAction("RS Up", throwIfNotFound: true);
        m_QTE_RSDown = m_QTE.FindAction("RS Down", throwIfNotFound: true);
        m_QTE_RSLeft = m_QTE.FindAction("RS Left", throwIfNotFound: true);
        m_QTE_RSRight = m_QTE.FindAction("RS Right", throwIfNotFound: true);
        m_QTE_RB = m_QTE.FindAction("RB", throwIfNotFound: true);
        m_QTE_LB = m_QTE.FindAction("LB", throwIfNotFound: true);
        m_QTE_RT = m_QTE.FindAction("RT", throwIfNotFound: true);
        m_QTE_LT = m_QTE.FindAction("LT", throwIfNotFound: true);
        m_QTE_DebugTriggerQTE = m_QTE.FindAction("DebugTriggerQTE", throwIfNotFound: true);
        m_QTE_Pause = m_QTE.FindAction("Pause", throwIfNotFound: true);
        // Card
        m_Card = asset.FindActionMap("Card", throwIfNotFound: true);
        m_Card_Deselect = m_Card.FindAction("Deselect", throwIfNotFound: true);
        m_Card_Select = m_Card.FindAction("Select", throwIfNotFound: true);
        m_Card_NavCardLeft = m_Card.FindAction("NavCardLeft", throwIfNotFound: true);
        m_Card_NavCardRight = m_Card.FindAction("NavCardRight", throwIfNotFound: true);
        m_Card_CameraUp = m_Card.FindAction("CameraUp", throwIfNotFound: true);
        m_Card_CameraDown = m_Card.FindAction("CameraDown", throwIfNotFound: true);
        m_Card_SetFinal = m_Card.FindAction("SetFinal", throwIfNotFound: true);
        m_Card_Pause = m_Card.FindAction("Pause", throwIfNotFound: true);
        m_Card_ManaView = m_Card.FindAction("ManaView", throwIfNotFound: true);
        // QTEWait
        m_QTEWait = asset.FindActionMap("QTEWait", throwIfNotFound: true);
        m_QTEWait_Pause = m_QTEWait.FindAction("Pause", throwIfNotFound: true);
        m_QTEWait_UnConfirm = m_QTEWait.FindAction("UnConfirm", throwIfNotFound: true);
    }

    ~@PlayerControls()
    {
        UnityEngine.Debug.Assert(!m_Player.enabled, "This will cause a leak and performance issues, PlayerControls.Player.Disable() has not been called.");
        UnityEngine.Debug.Assert(!m_UI.enabled, "This will cause a leak and performance issues, PlayerControls.UI.Disable() has not been called.");
        UnityEngine.Debug.Assert(!m_QTE.enabled, "This will cause a leak and performance issues, PlayerControls.QTE.Disable() has not been called.");
        UnityEngine.Debug.Assert(!m_Card.enabled, "This will cause a leak and performance issues, PlayerControls.Card.Disable() has not been called.");
        UnityEngine.Debug.Assert(!m_QTEWait.enabled, "This will cause a leak and performance issues, PlayerControls.QTEWait.Disable() has not been called.");
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Player
    private readonly InputActionMap m_Player;
    private List<IPlayerActions> m_PlayerActionsCallbackInterfaces = new List<IPlayerActions>();
    private readonly InputAction m_Player_FingerLeft;
    private readonly InputAction m_Player_FingerRight;
    private readonly InputAction m_Player_Pause;
    private readonly InputAction m_Player_Cancel;
    private readonly InputAction m_Player_SelectFinger;
    private readonly InputAction m_Player_DebugHandSwap;
    private readonly InputAction m_Player_PlayCards;
    public struct PlayerActions
    {
        private @PlayerControls m_Wrapper;
        public PlayerActions(@PlayerControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @FingerLeft => m_Wrapper.m_Player_FingerLeft;
        public InputAction @FingerRight => m_Wrapper.m_Player_FingerRight;
        public InputAction @Pause => m_Wrapper.m_Player_Pause;
        public InputAction @Cancel => m_Wrapper.m_Player_Cancel;
        public InputAction @SelectFinger => m_Wrapper.m_Player_SelectFinger;
        public InputAction @DebugHandSwap => m_Wrapper.m_Player_DebugHandSwap;
        public InputAction @PlayCards => m_Wrapper.m_Player_PlayCards;
        public InputActionMap Get() { return m_Wrapper.m_Player; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerActions set) { return set.Get(); }
        public void AddCallbacks(IPlayerActions instance)
        {
            if (instance == null || m_Wrapper.m_PlayerActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PlayerActionsCallbackInterfaces.Add(instance);
            @FingerLeft.started += instance.OnFingerLeft;
            @FingerLeft.performed += instance.OnFingerLeft;
            @FingerLeft.canceled += instance.OnFingerLeft;
            @FingerRight.started += instance.OnFingerRight;
            @FingerRight.performed += instance.OnFingerRight;
            @FingerRight.canceled += instance.OnFingerRight;
            @Pause.started += instance.OnPause;
            @Pause.performed += instance.OnPause;
            @Pause.canceled += instance.OnPause;
            @Cancel.started += instance.OnCancel;
            @Cancel.performed += instance.OnCancel;
            @Cancel.canceled += instance.OnCancel;
            @SelectFinger.started += instance.OnSelectFinger;
            @SelectFinger.performed += instance.OnSelectFinger;
            @SelectFinger.canceled += instance.OnSelectFinger;
            @DebugHandSwap.started += instance.OnDebugHandSwap;
            @DebugHandSwap.performed += instance.OnDebugHandSwap;
            @DebugHandSwap.canceled += instance.OnDebugHandSwap;
            @PlayCards.started += instance.OnPlayCards;
            @PlayCards.performed += instance.OnPlayCards;
            @PlayCards.canceled += instance.OnPlayCards;
        }

        private void UnregisterCallbacks(IPlayerActions instance)
        {
            @FingerLeft.started -= instance.OnFingerLeft;
            @FingerLeft.performed -= instance.OnFingerLeft;
            @FingerLeft.canceled -= instance.OnFingerLeft;
            @FingerRight.started -= instance.OnFingerRight;
            @FingerRight.performed -= instance.OnFingerRight;
            @FingerRight.canceled -= instance.OnFingerRight;
            @Pause.started -= instance.OnPause;
            @Pause.performed -= instance.OnPause;
            @Pause.canceled -= instance.OnPause;
            @Cancel.started -= instance.OnCancel;
            @Cancel.performed -= instance.OnCancel;
            @Cancel.canceled -= instance.OnCancel;
            @SelectFinger.started -= instance.OnSelectFinger;
            @SelectFinger.performed -= instance.OnSelectFinger;
            @SelectFinger.canceled -= instance.OnSelectFinger;
            @DebugHandSwap.started -= instance.OnDebugHandSwap;
            @DebugHandSwap.performed -= instance.OnDebugHandSwap;
            @DebugHandSwap.canceled -= instance.OnDebugHandSwap;
            @PlayCards.started -= instance.OnPlayCards;
            @PlayCards.performed -= instance.OnPlayCards;
            @PlayCards.canceled -= instance.OnPlayCards;
        }

        public void RemoveCallbacks(IPlayerActions instance)
        {
            if (m_Wrapper.m_PlayerActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPlayerActions instance)
        {
            foreach (var item in m_Wrapper.m_PlayerActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PlayerActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public PlayerActions @Player => new PlayerActions(this);

    // UI
    private readonly InputActionMap m_UI;
    private List<IUIActions> m_UIActionsCallbackInterfaces = new List<IUIActions>();
    private readonly InputAction m_UI_UI_Move;
    private readonly InputAction m_UI_UI_Select;
    public struct UIActions
    {
        private @PlayerControls m_Wrapper;
        public UIActions(@PlayerControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @UI_Move => m_Wrapper.m_UI_UI_Move;
        public InputAction @UI_Select => m_Wrapper.m_UI_UI_Select;
        public InputActionMap Get() { return m_Wrapper.m_UI; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(UIActions set) { return set.Get(); }
        public void AddCallbacks(IUIActions instance)
        {
            if (instance == null || m_Wrapper.m_UIActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_UIActionsCallbackInterfaces.Add(instance);
            @UI_Move.started += instance.OnUI_Move;
            @UI_Move.performed += instance.OnUI_Move;
            @UI_Move.canceled += instance.OnUI_Move;
            @UI_Select.started += instance.OnUI_Select;
            @UI_Select.performed += instance.OnUI_Select;
            @UI_Select.canceled += instance.OnUI_Select;
        }

        private void UnregisterCallbacks(IUIActions instance)
        {
            @UI_Move.started -= instance.OnUI_Move;
            @UI_Move.performed -= instance.OnUI_Move;
            @UI_Move.canceled -= instance.OnUI_Move;
            @UI_Select.started -= instance.OnUI_Select;
            @UI_Select.performed -= instance.OnUI_Select;
            @UI_Select.canceled -= instance.OnUI_Select;
        }

        public void RemoveCallbacks(IUIActions instance)
        {
            if (m_Wrapper.m_UIActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IUIActions instance)
        {
            foreach (var item in m_Wrapper.m_UIActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_UIActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public UIActions @UI => new UIActions(this);

    // QTE
    private readonly InputActionMap m_QTE;
    private List<IQTEActions> m_QTEActionsCallbackInterfaces = new List<IQTEActions>();
    private readonly InputAction m_QTE_North;
    private readonly InputAction m_QTE_South;
    private readonly InputAction m_QTE_East;
    private readonly InputAction m_QTE_West;
    private readonly InputAction m_QTE_DPadUp;
    private readonly InputAction m_QTE_DPadDown;
    private readonly InputAction m_QTE_DPadLeft;
    private readonly InputAction m_QTE_DPadRight;
    private readonly InputAction m_QTE_LSUp;
    private readonly InputAction m_QTE_LSDown;
    private readonly InputAction m_QTE_LSLeft;
    private readonly InputAction m_QTE_LSRight;
    private readonly InputAction m_QTE_RSUp;
    private readonly InputAction m_QTE_RSDown;
    private readonly InputAction m_QTE_RSLeft;
    private readonly InputAction m_QTE_RSRight;
    private readonly InputAction m_QTE_RB;
    private readonly InputAction m_QTE_LB;
    private readonly InputAction m_QTE_RT;
    private readonly InputAction m_QTE_LT;
    private readonly InputAction m_QTE_DebugTriggerQTE;
    private readonly InputAction m_QTE_Pause;
    public struct QTEActions
    {
        private @PlayerControls m_Wrapper;
        public QTEActions(@PlayerControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @North => m_Wrapper.m_QTE_North;
        public InputAction @South => m_Wrapper.m_QTE_South;
        public InputAction @East => m_Wrapper.m_QTE_East;
        public InputAction @West => m_Wrapper.m_QTE_West;
        public InputAction @DPadUp => m_Wrapper.m_QTE_DPadUp;
        public InputAction @DPadDown => m_Wrapper.m_QTE_DPadDown;
        public InputAction @DPadLeft => m_Wrapper.m_QTE_DPadLeft;
        public InputAction @DPadRight => m_Wrapper.m_QTE_DPadRight;
        public InputAction @LSUp => m_Wrapper.m_QTE_LSUp;
        public InputAction @LSDown => m_Wrapper.m_QTE_LSDown;
        public InputAction @LSLeft => m_Wrapper.m_QTE_LSLeft;
        public InputAction @LSRight => m_Wrapper.m_QTE_LSRight;
        public InputAction @RSUp => m_Wrapper.m_QTE_RSUp;
        public InputAction @RSDown => m_Wrapper.m_QTE_RSDown;
        public InputAction @RSLeft => m_Wrapper.m_QTE_RSLeft;
        public InputAction @RSRight => m_Wrapper.m_QTE_RSRight;
        public InputAction @RB => m_Wrapper.m_QTE_RB;
        public InputAction @LB => m_Wrapper.m_QTE_LB;
        public InputAction @RT => m_Wrapper.m_QTE_RT;
        public InputAction @LT => m_Wrapper.m_QTE_LT;
        public InputAction @DebugTriggerQTE => m_Wrapper.m_QTE_DebugTriggerQTE;
        public InputAction @Pause => m_Wrapper.m_QTE_Pause;
        public InputActionMap Get() { return m_Wrapper.m_QTE; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(QTEActions set) { return set.Get(); }
        public void AddCallbacks(IQTEActions instance)
        {
            if (instance == null || m_Wrapper.m_QTEActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_QTEActionsCallbackInterfaces.Add(instance);
            @North.started += instance.OnNorth;
            @North.performed += instance.OnNorth;
            @North.canceled += instance.OnNorth;
            @South.started += instance.OnSouth;
            @South.performed += instance.OnSouth;
            @South.canceled += instance.OnSouth;
            @East.started += instance.OnEast;
            @East.performed += instance.OnEast;
            @East.canceled += instance.OnEast;
            @West.started += instance.OnWest;
            @West.performed += instance.OnWest;
            @West.canceled += instance.OnWest;
            @DPadUp.started += instance.OnDPadUp;
            @DPadUp.performed += instance.OnDPadUp;
            @DPadUp.canceled += instance.OnDPadUp;
            @DPadDown.started += instance.OnDPadDown;
            @DPadDown.performed += instance.OnDPadDown;
            @DPadDown.canceled += instance.OnDPadDown;
            @DPadLeft.started += instance.OnDPadLeft;
            @DPadLeft.performed += instance.OnDPadLeft;
            @DPadLeft.canceled += instance.OnDPadLeft;
            @DPadRight.started += instance.OnDPadRight;
            @DPadRight.performed += instance.OnDPadRight;
            @DPadRight.canceled += instance.OnDPadRight;
            @LSUp.started += instance.OnLSUp;
            @LSUp.performed += instance.OnLSUp;
            @LSUp.canceled += instance.OnLSUp;
            @LSDown.started += instance.OnLSDown;
            @LSDown.performed += instance.OnLSDown;
            @LSDown.canceled += instance.OnLSDown;
            @LSLeft.started += instance.OnLSLeft;
            @LSLeft.performed += instance.OnLSLeft;
            @LSLeft.canceled += instance.OnLSLeft;
            @LSRight.started += instance.OnLSRight;
            @LSRight.performed += instance.OnLSRight;
            @LSRight.canceled += instance.OnLSRight;
            @RSUp.started += instance.OnRSUp;
            @RSUp.performed += instance.OnRSUp;
            @RSUp.canceled += instance.OnRSUp;
            @RSDown.started += instance.OnRSDown;
            @RSDown.performed += instance.OnRSDown;
            @RSDown.canceled += instance.OnRSDown;
            @RSLeft.started += instance.OnRSLeft;
            @RSLeft.performed += instance.OnRSLeft;
            @RSLeft.canceled += instance.OnRSLeft;
            @RSRight.started += instance.OnRSRight;
            @RSRight.performed += instance.OnRSRight;
            @RSRight.canceled += instance.OnRSRight;
            @RB.started += instance.OnRB;
            @RB.performed += instance.OnRB;
            @RB.canceled += instance.OnRB;
            @LB.started += instance.OnLB;
            @LB.performed += instance.OnLB;
            @LB.canceled += instance.OnLB;
            @RT.started += instance.OnRT;
            @RT.performed += instance.OnRT;
            @RT.canceled += instance.OnRT;
            @LT.started += instance.OnLT;
            @LT.performed += instance.OnLT;
            @LT.canceled += instance.OnLT;
            @DebugTriggerQTE.started += instance.OnDebugTriggerQTE;
            @DebugTriggerQTE.performed += instance.OnDebugTriggerQTE;
            @DebugTriggerQTE.canceled += instance.OnDebugTriggerQTE;
            @Pause.started += instance.OnPause;
            @Pause.performed += instance.OnPause;
            @Pause.canceled += instance.OnPause;
        }

        private void UnregisterCallbacks(IQTEActions instance)
        {
            @North.started -= instance.OnNorth;
            @North.performed -= instance.OnNorth;
            @North.canceled -= instance.OnNorth;
            @South.started -= instance.OnSouth;
            @South.performed -= instance.OnSouth;
            @South.canceled -= instance.OnSouth;
            @East.started -= instance.OnEast;
            @East.performed -= instance.OnEast;
            @East.canceled -= instance.OnEast;
            @West.started -= instance.OnWest;
            @West.performed -= instance.OnWest;
            @West.canceled -= instance.OnWest;
            @DPadUp.started -= instance.OnDPadUp;
            @DPadUp.performed -= instance.OnDPadUp;
            @DPadUp.canceled -= instance.OnDPadUp;
            @DPadDown.started -= instance.OnDPadDown;
            @DPadDown.performed -= instance.OnDPadDown;
            @DPadDown.canceled -= instance.OnDPadDown;
            @DPadLeft.started -= instance.OnDPadLeft;
            @DPadLeft.performed -= instance.OnDPadLeft;
            @DPadLeft.canceled -= instance.OnDPadLeft;
            @DPadRight.started -= instance.OnDPadRight;
            @DPadRight.performed -= instance.OnDPadRight;
            @DPadRight.canceled -= instance.OnDPadRight;
            @LSUp.started -= instance.OnLSUp;
            @LSUp.performed -= instance.OnLSUp;
            @LSUp.canceled -= instance.OnLSUp;
            @LSDown.started -= instance.OnLSDown;
            @LSDown.performed -= instance.OnLSDown;
            @LSDown.canceled -= instance.OnLSDown;
            @LSLeft.started -= instance.OnLSLeft;
            @LSLeft.performed -= instance.OnLSLeft;
            @LSLeft.canceled -= instance.OnLSLeft;
            @LSRight.started -= instance.OnLSRight;
            @LSRight.performed -= instance.OnLSRight;
            @LSRight.canceled -= instance.OnLSRight;
            @RSUp.started -= instance.OnRSUp;
            @RSUp.performed -= instance.OnRSUp;
            @RSUp.canceled -= instance.OnRSUp;
            @RSDown.started -= instance.OnRSDown;
            @RSDown.performed -= instance.OnRSDown;
            @RSDown.canceled -= instance.OnRSDown;
            @RSLeft.started -= instance.OnRSLeft;
            @RSLeft.performed -= instance.OnRSLeft;
            @RSLeft.canceled -= instance.OnRSLeft;
            @RSRight.started -= instance.OnRSRight;
            @RSRight.performed -= instance.OnRSRight;
            @RSRight.canceled -= instance.OnRSRight;
            @RB.started -= instance.OnRB;
            @RB.performed -= instance.OnRB;
            @RB.canceled -= instance.OnRB;
            @LB.started -= instance.OnLB;
            @LB.performed -= instance.OnLB;
            @LB.canceled -= instance.OnLB;
            @RT.started -= instance.OnRT;
            @RT.performed -= instance.OnRT;
            @RT.canceled -= instance.OnRT;
            @LT.started -= instance.OnLT;
            @LT.performed -= instance.OnLT;
            @LT.canceled -= instance.OnLT;
            @DebugTriggerQTE.started -= instance.OnDebugTriggerQTE;
            @DebugTriggerQTE.performed -= instance.OnDebugTriggerQTE;
            @DebugTriggerQTE.canceled -= instance.OnDebugTriggerQTE;
            @Pause.started -= instance.OnPause;
            @Pause.performed -= instance.OnPause;
            @Pause.canceled -= instance.OnPause;
        }

        public void RemoveCallbacks(IQTEActions instance)
        {
            if (m_Wrapper.m_QTEActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IQTEActions instance)
        {
            foreach (var item in m_Wrapper.m_QTEActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_QTEActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public QTEActions @QTE => new QTEActions(this);

    // Card
    private readonly InputActionMap m_Card;
    private List<ICardActions> m_CardActionsCallbackInterfaces = new List<ICardActions>();
    private readonly InputAction m_Card_Deselect;
    private readonly InputAction m_Card_Select;
    private readonly InputAction m_Card_NavCardLeft;
    private readonly InputAction m_Card_NavCardRight;
    private readonly InputAction m_Card_CameraUp;
    private readonly InputAction m_Card_CameraDown;
    private readonly InputAction m_Card_SetFinal;
    private readonly InputAction m_Card_Pause;
    private readonly InputAction m_Card_ManaView;
    public struct CardActions
    {
        private @PlayerControls m_Wrapper;
        public CardActions(@PlayerControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Deselect => m_Wrapper.m_Card_Deselect;
        public InputAction @Select => m_Wrapper.m_Card_Select;
        public InputAction @NavCardLeft => m_Wrapper.m_Card_NavCardLeft;
        public InputAction @NavCardRight => m_Wrapper.m_Card_NavCardRight;
        public InputAction @CameraUp => m_Wrapper.m_Card_CameraUp;
        public InputAction @CameraDown => m_Wrapper.m_Card_CameraDown;
        public InputAction @SetFinal => m_Wrapper.m_Card_SetFinal;
        public InputAction @Pause => m_Wrapper.m_Card_Pause;
        public InputAction @ManaView => m_Wrapper.m_Card_ManaView;
        public InputActionMap Get() { return m_Wrapper.m_Card; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(CardActions set) { return set.Get(); }
        public void AddCallbacks(ICardActions instance)
        {
            if (instance == null || m_Wrapper.m_CardActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_CardActionsCallbackInterfaces.Add(instance);
            @Deselect.started += instance.OnDeselect;
            @Deselect.performed += instance.OnDeselect;
            @Deselect.canceled += instance.OnDeselect;
            @Select.started += instance.OnSelect;
            @Select.performed += instance.OnSelect;
            @Select.canceled += instance.OnSelect;
            @NavCardLeft.started += instance.OnNavCardLeft;
            @NavCardLeft.performed += instance.OnNavCardLeft;
            @NavCardLeft.canceled += instance.OnNavCardLeft;
            @NavCardRight.started += instance.OnNavCardRight;
            @NavCardRight.performed += instance.OnNavCardRight;
            @NavCardRight.canceled += instance.OnNavCardRight;
            @CameraUp.started += instance.OnCameraUp;
            @CameraUp.performed += instance.OnCameraUp;
            @CameraUp.canceled += instance.OnCameraUp;
            @CameraDown.started += instance.OnCameraDown;
            @CameraDown.performed += instance.OnCameraDown;
            @CameraDown.canceled += instance.OnCameraDown;
            @SetFinal.started += instance.OnSetFinal;
            @SetFinal.performed += instance.OnSetFinal;
            @SetFinal.canceled += instance.OnSetFinal;
            @Pause.started += instance.OnPause;
            @Pause.performed += instance.OnPause;
            @Pause.canceled += instance.OnPause;
            @ManaView.started += instance.OnManaView;
            @ManaView.performed += instance.OnManaView;
            @ManaView.canceled += instance.OnManaView;
        }

        private void UnregisterCallbacks(ICardActions instance)
        {
            @Deselect.started -= instance.OnDeselect;
            @Deselect.performed -= instance.OnDeselect;
            @Deselect.canceled -= instance.OnDeselect;
            @Select.started -= instance.OnSelect;
            @Select.performed -= instance.OnSelect;
            @Select.canceled -= instance.OnSelect;
            @NavCardLeft.started -= instance.OnNavCardLeft;
            @NavCardLeft.performed -= instance.OnNavCardLeft;
            @NavCardLeft.canceled -= instance.OnNavCardLeft;
            @NavCardRight.started -= instance.OnNavCardRight;
            @NavCardRight.performed -= instance.OnNavCardRight;
            @NavCardRight.canceled -= instance.OnNavCardRight;
            @CameraUp.started -= instance.OnCameraUp;
            @CameraUp.performed -= instance.OnCameraUp;
            @CameraUp.canceled -= instance.OnCameraUp;
            @CameraDown.started -= instance.OnCameraDown;
            @CameraDown.performed -= instance.OnCameraDown;
            @CameraDown.canceled -= instance.OnCameraDown;
            @SetFinal.started -= instance.OnSetFinal;
            @SetFinal.performed -= instance.OnSetFinal;
            @SetFinal.canceled -= instance.OnSetFinal;
            @Pause.started -= instance.OnPause;
            @Pause.performed -= instance.OnPause;
            @Pause.canceled -= instance.OnPause;
            @ManaView.started -= instance.OnManaView;
            @ManaView.performed -= instance.OnManaView;
            @ManaView.canceled -= instance.OnManaView;
        }

        public void RemoveCallbacks(ICardActions instance)
        {
            if (m_Wrapper.m_CardActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(ICardActions instance)
        {
            foreach (var item in m_Wrapper.m_CardActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_CardActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public CardActions @Card => new CardActions(this);

    // QTEWait
    private readonly InputActionMap m_QTEWait;
    private List<IQTEWaitActions> m_QTEWaitActionsCallbackInterfaces = new List<IQTEWaitActions>();
    private readonly InputAction m_QTEWait_Pause;
    private readonly InputAction m_QTEWait_UnConfirm;
    public struct QTEWaitActions
    {
        private @PlayerControls m_Wrapper;
        public QTEWaitActions(@PlayerControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Pause => m_Wrapper.m_QTEWait_Pause;
        public InputAction @UnConfirm => m_Wrapper.m_QTEWait_UnConfirm;
        public InputActionMap Get() { return m_Wrapper.m_QTEWait; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(QTEWaitActions set) { return set.Get(); }
        public void AddCallbacks(IQTEWaitActions instance)
        {
            if (instance == null || m_Wrapper.m_QTEWaitActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_QTEWaitActionsCallbackInterfaces.Add(instance);
            @Pause.started += instance.OnPause;
            @Pause.performed += instance.OnPause;
            @Pause.canceled += instance.OnPause;
            @UnConfirm.started += instance.OnUnConfirm;
            @UnConfirm.performed += instance.OnUnConfirm;
            @UnConfirm.canceled += instance.OnUnConfirm;
        }

        private void UnregisterCallbacks(IQTEWaitActions instance)
        {
            @Pause.started -= instance.OnPause;
            @Pause.performed -= instance.OnPause;
            @Pause.canceled -= instance.OnPause;
            @UnConfirm.started -= instance.OnUnConfirm;
            @UnConfirm.performed -= instance.OnUnConfirm;
            @UnConfirm.canceled -= instance.OnUnConfirm;
        }

        public void RemoveCallbacks(IQTEWaitActions instance)
        {
            if (m_Wrapper.m_QTEWaitActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IQTEWaitActions instance)
        {
            foreach (var item in m_Wrapper.m_QTEWaitActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_QTEWaitActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public QTEWaitActions @QTEWait => new QTEWaitActions(this);
    private int m_KeyboardMouseSchemeIndex = -1;
    public InputControlScheme KeyboardMouseScheme
    {
        get
        {
            if (m_KeyboardMouseSchemeIndex == -1) m_KeyboardMouseSchemeIndex = asset.FindControlSchemeIndex("Keyboard&Mouse");
            return asset.controlSchemes[m_KeyboardMouseSchemeIndex];
        }
    }
    private int m_GamepadSchemeIndex = -1;
    public InputControlScheme GamepadScheme
    {
        get
        {
            if (m_GamepadSchemeIndex == -1) m_GamepadSchemeIndex = asset.FindControlSchemeIndex("Gamepad");
            return asset.controlSchemes[m_GamepadSchemeIndex];
        }
    }
    private int m_TouchSchemeIndex = -1;
    public InputControlScheme TouchScheme
    {
        get
        {
            if (m_TouchSchemeIndex == -1) m_TouchSchemeIndex = asset.FindControlSchemeIndex("Touch");
            return asset.controlSchemes[m_TouchSchemeIndex];
        }
    }
    private int m_JoystickSchemeIndex = -1;
    public InputControlScheme JoystickScheme
    {
        get
        {
            if (m_JoystickSchemeIndex == -1) m_JoystickSchemeIndex = asset.FindControlSchemeIndex("Joystick");
            return asset.controlSchemes[m_JoystickSchemeIndex];
        }
    }
    private int m_XRSchemeIndex = -1;
    public InputControlScheme XRScheme
    {
        get
        {
            if (m_XRSchemeIndex == -1) m_XRSchemeIndex = asset.FindControlSchemeIndex("XR");
            return asset.controlSchemes[m_XRSchemeIndex];
        }
    }
    public interface IPlayerActions
    {
        void OnFingerLeft(InputAction.CallbackContext context);
        void OnFingerRight(InputAction.CallbackContext context);
        void OnPause(InputAction.CallbackContext context);
        void OnCancel(InputAction.CallbackContext context);
        void OnSelectFinger(InputAction.CallbackContext context);
        void OnDebugHandSwap(InputAction.CallbackContext context);
        void OnPlayCards(InputAction.CallbackContext context);
    }
    public interface IUIActions
    {
        void OnUI_Move(InputAction.CallbackContext context);
        void OnUI_Select(InputAction.CallbackContext context);
    }
    public interface IQTEActions
    {
        void OnNorth(InputAction.CallbackContext context);
        void OnSouth(InputAction.CallbackContext context);
        void OnEast(InputAction.CallbackContext context);
        void OnWest(InputAction.CallbackContext context);
        void OnDPadUp(InputAction.CallbackContext context);
        void OnDPadDown(InputAction.CallbackContext context);
        void OnDPadLeft(InputAction.CallbackContext context);
        void OnDPadRight(InputAction.CallbackContext context);
        void OnLSUp(InputAction.CallbackContext context);
        void OnLSDown(InputAction.CallbackContext context);
        void OnLSLeft(InputAction.CallbackContext context);
        void OnLSRight(InputAction.CallbackContext context);
        void OnRSUp(InputAction.CallbackContext context);
        void OnRSDown(InputAction.CallbackContext context);
        void OnRSLeft(InputAction.CallbackContext context);
        void OnRSRight(InputAction.CallbackContext context);
        void OnRB(InputAction.CallbackContext context);
        void OnLB(InputAction.CallbackContext context);
        void OnRT(InputAction.CallbackContext context);
        void OnLT(InputAction.CallbackContext context);
        void OnDebugTriggerQTE(InputAction.CallbackContext context);
        void OnPause(InputAction.CallbackContext context);
    }
    public interface ICardActions
    {
        void OnDeselect(InputAction.CallbackContext context);
        void OnSelect(InputAction.CallbackContext context);
        void OnNavCardLeft(InputAction.CallbackContext context);
        void OnNavCardRight(InputAction.CallbackContext context);
        void OnCameraUp(InputAction.CallbackContext context);
        void OnCameraDown(InputAction.CallbackContext context);
        void OnSetFinal(InputAction.CallbackContext context);
        void OnPause(InputAction.CallbackContext context);
        void OnManaView(InputAction.CallbackContext context);
    }
    public interface IQTEWaitActions
    {
        void OnPause(InputAction.CallbackContext context);
        void OnUnConfirm(InputAction.CallbackContext context);
    }
}
