//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Controls/PlayerControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerControls: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerControls"",
    ""maps"": [
        {
            ""name"": ""Player"",
            ""id"": ""ff5a7c2d-1673-4ce8-b028-73cd17c4c1f7"",
            ""actions"": [
                {
                    ""name"": ""NavCardLeft"",
                    ""type"": ""Button"",
                    ""id"": ""b8d5d5ce-1587-475d-aefc-f5e06a023f6b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""NavCardRight"",
                    ""type"": ""Button"",
                    ""id"": ""fc879357-ef2f-48fa-b82a-60dcbaaec360"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Navigate Finger Up"",
                    ""type"": ""Button"",
                    ""id"": ""6f7d127b-4cc3-4874-8694-f43676a77080"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Navigate Finger Down"",
                    ""type"": ""Button"",
                    ""id"": ""d51820a4-bcf2-4aa8-aeb2-6c4b2e770ae2"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""NavigateFingerLeft"",
                    ""type"": ""Button"",
                    ""id"": ""23ca8a23-c3f2-4108-b862-ab74ec3a7b26"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""NavigateFingerRight"",
                    ""type"": ""Button"",
                    ""id"": ""4905f20d-9850-4556-bdbb-459c86a23920"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""See Player Health"",
                    ""type"": ""Button"",
                    ""id"": ""1d9309d1-71b0-47fc-9ee4-49b594807a7f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""See Enemy Health"",
                    ""type"": ""Button"",
                    ""id"": ""6d8b4439-50da-4652-b2b5-c7b63b2ce153"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""See Player Mana"",
                    ""type"": ""Button"",
                    ""id"": ""913fb6a1-50ae-4d2d-9ed5-79da5f504553"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""See Enemy Mana"",
                    ""type"": ""Button"",
                    ""id"": ""6a744a52-9b29-4a6f-b863-27130b8977bc"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Pause"",
                    ""type"": ""Button"",
                    ""id"": ""b848d38f-42b4-4cd7-96c6-96db386dd32a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Deselect"",
                    ""type"": ""Button"",
                    ""id"": ""4a146562-77fe-4804-9d9e-9ad294970083"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Select"",
                    ""type"": ""Button"",
                    ""id"": ""a19647d5-ad39-46ae-8644-3c2b6f22e7f5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Swap Player Hands"",
                    ""type"": ""Button"",
                    ""id"": ""941744c0-fa64-47b3-9a45-5e8713eb7747"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""c1f7a91b-d0fd-4a62-997e-7fb9b69bf235"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Gamepad"",
                    ""action"": ""See Player Health"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8c8e490b-c610-4785-884f-f04217b23ca4"",
                    ""path"": ""<Pointer>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard&Mouse;Touch"",
                    ""action"": ""See Player Health"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3e5f5442-8668-4b27-a940-df99bad7e831"",
                    ""path"": ""<Joystick>/{Hatswitch}"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Joystick"",
                    ""action"": ""See Player Health"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4411f632-50f2-4cb9-b3de-2627f4053aaf"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""See Enemy Health"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ecac374c-e928-462c-b101-161f7f358667"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""See Player Mana"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ded686ba-ccd8-47d0-a587-69f07da49c0a"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""See Enemy Mana"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""13f40110-da8d-4d85-b413-a2813252d66c"",
                    ""path"": ""<Gamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cbcd22b9-3a5e-4b7a-a58e-3c1324bada0e"",
                    ""path"": ""<Keyboard>/backspace"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""69db217e-a6d4-4db1-b387-a78d7b9f46e3"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Deselect"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0ebe438a-0731-4607-95ac-ff4c7c4cecaf"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Select"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""da12a368-c48f-4f1c-b4d5-d470bd67708e"",
                    ""path"": ""<Gamepad>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Navigate Finger Up"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3dfd3ae1-29d2-41f6-8fc5-124d91627fa8"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Navigate Finger Up"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""71409c87-e6fc-4575-bcb9-fc5b662280f9"",
                    ""path"": ""<Gamepad>/dpad/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Navigate Finger Down"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a689474b-c02a-4986-b2b0-46835fd24e12"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Navigate Finger Down"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""30d75d9d-89bc-4e03-a9ee-b940b71e2b38"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Swap Player Hands"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""14a344f3-8bf0-4c13-8565-1b87a2dac3da"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""NavCardLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2ded4a5b-57ac-4750-9eb8-dd5b24648c42"",
                    ""path"": ""<Gamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""NavCardLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c7a71afd-4f6b-496e-b997-bd74760ca067"",
                    ""path"": ""<Gamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""NavCardLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""204bdebe-7a66-40f2-a71d-ddfee106b462"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""NavCardRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9b1434a3-bc3f-4cc5-83a1-f10166c95a24"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""NavCardRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1f938129-7371-44b7-b45c-221c7a7ceec0"",
                    ""path"": ""<Gamepad>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""NavCardRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""482fda32-3950-4a72-a005-8ddff100507f"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""NavigateFingerLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""65a29646-c2a4-486b-973c-dfb96157356c"",
                    ""path"": ""<Gamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""NavigateFingerLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""22a7ab3e-8876-49bd-bd89-a376371c6008"",
                    ""path"": ""<Gamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""NavigateFingerLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""dbe550bb-7ba4-470e-8a93-c1c140f8b8aa"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""NavigateFingerRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a8af2a34-0581-4239-ba56-8b0694dc3d2d"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""NavigateFingerRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5d0cc5bf-1c47-4be8-92f8-632e01b19e1b"",
                    ""path"": ""<Gamepad>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""NavigateFingerRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""UI"",
            ""id"": ""2ae069f1-6793-41d6-82fe-4dec30dfc3b5"",
            ""actions"": [
                {
                    ""name"": ""UI_Move"",
                    ""type"": ""PassThrough"",
                    ""id"": ""627ad011-9d32-454c-933f-afb2b9b824a5"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""UI_Select"",
                    ""type"": ""Button"",
                    ""id"": ""97c9da3b-aa1e-43bb-adec-7c66f7c4264f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""Dpad"",
                    ""id"": ""4782503e-3ec7-4437-bda6-1125350c6834"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UI_Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""019c3218-ecd5-462b-94ed-f0ac77334b5b"",
                    ""path"": ""<Gamepad>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""UI_Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""b6a1693e-c79d-409c-be48-0a8da4ff3711"",
                    ""path"": ""<Gamepad>/dpad/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""UI_Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""b66ea053-1ab7-4caf-8ed1-4c144c5cb640"",
                    ""path"": ""<Gamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""UI_Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""b69d7ced-51d9-4e20-a45f-e9f7380f1bfe"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""UI_Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""LeftJoystick"",
                    ""id"": ""ff786e47-9728-4dc6-a45b-9abd62aab166"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UI_Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""e82b3940-cf62-48a6-9f43-f9d7799a982b"",
                    ""path"": ""<Gamepad>/leftStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""UI_Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""434b660d-e841-41b2-9e3c-f73de3adaadb"",
                    ""path"": ""<Gamepad>/leftStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""UI_Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""f7da9f91-1b72-4ba2-8550-534fc0fce7fb"",
                    ""path"": ""<Gamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""UI_Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""9dcd3d3e-e34d-4bfd-8bbe-7b15b99421c2"",
                    ""path"": ""<Gamepad>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""UI_Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Keyboard"",
                    ""id"": ""6c3c8306-87f6-4f95-9b36-47242c0e098b"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UI_Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""0a25fcd8-16f3-425d-aed1-3c3223b2ec9b"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""UI_Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""204e95f7-f064-4f0f-ad8d-6f927651869f"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""UI_Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""163bb74d-9581-4e51-9e31-d5202ddd8cca"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""UI_Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""95714239-2807-401e-bcd0-407468df0435"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""UI_Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""7d1074ec-27d6-4423-a530-1603f349fe31"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UI_Select"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c2ece352-1d7d-448c-a464-101e2b41a0f1"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UI_Select"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Keyboard&Mouse"",
            ""bindingGroup"": ""Keyboard&Mouse"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<Mouse>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""Gamepad"",
            ""bindingGroup"": ""Gamepad"",
            ""devices"": [
                {
                    ""devicePath"": ""<Gamepad>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""Touch"",
            ""bindingGroup"": ""Touch"",
            ""devices"": [
                {
                    ""devicePath"": ""<Touchscreen>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""Joystick"",
            ""bindingGroup"": ""Joystick"",
            ""devices"": [
                {
                    ""devicePath"": ""<Joystick>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""XR"",
            ""bindingGroup"": ""XR"",
            ""devices"": [
                {
                    ""devicePath"": ""<XRController>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // Player
        m_Player = asset.FindActionMap("Player", throwIfNotFound: true);
        m_Player_NavCardLeft = m_Player.FindAction("NavCardLeft", throwIfNotFound: true);
        m_Player_NavCardRight = m_Player.FindAction("NavCardRight", throwIfNotFound: true);
        m_Player_NavigateFingerUp = m_Player.FindAction("Navigate Finger Up", throwIfNotFound: true);
        m_Player_NavigateFingerDown = m_Player.FindAction("Navigate Finger Down", throwIfNotFound: true);
        m_Player_NavigateFingerLeft = m_Player.FindAction("NavigateFingerLeft", throwIfNotFound: true);
        m_Player_NavigateFingerRight = m_Player.FindAction("NavigateFingerRight", throwIfNotFound: true);
        m_Player_SeePlayerHealth = m_Player.FindAction("See Player Health", throwIfNotFound: true);
        m_Player_SeeEnemyHealth = m_Player.FindAction("See Enemy Health", throwIfNotFound: true);
        m_Player_SeePlayerMana = m_Player.FindAction("See Player Mana", throwIfNotFound: true);
        m_Player_SeeEnemyMana = m_Player.FindAction("See Enemy Mana", throwIfNotFound: true);
        m_Player_Pause = m_Player.FindAction("Pause", throwIfNotFound: true);
        m_Player_Deselect = m_Player.FindAction("Deselect", throwIfNotFound: true);
        m_Player_Select = m_Player.FindAction("Select", throwIfNotFound: true);
        m_Player_SwapPlayerHands = m_Player.FindAction("Swap Player Hands", throwIfNotFound: true);
        // UI
        m_UI = asset.FindActionMap("UI", throwIfNotFound: true);
        m_UI_UI_Move = m_UI.FindAction("UI_Move", throwIfNotFound: true);
        m_UI_UI_Select = m_UI.FindAction("UI_Select", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Player
    private readonly InputActionMap m_Player;
    private List<IPlayerActions> m_PlayerActionsCallbackInterfaces = new List<IPlayerActions>();
    private readonly InputAction m_Player_NavCardLeft;
    private readonly InputAction m_Player_NavCardRight;
    private readonly InputAction m_Player_NavigateFingerUp;
    private readonly InputAction m_Player_NavigateFingerDown;
    private readonly InputAction m_Player_NavigateFingerLeft;
    private readonly InputAction m_Player_NavigateFingerRight;
    private readonly InputAction m_Player_SeePlayerHealth;
    private readonly InputAction m_Player_SeeEnemyHealth;
    private readonly InputAction m_Player_SeePlayerMana;
    private readonly InputAction m_Player_SeeEnemyMana;
    private readonly InputAction m_Player_Pause;
    private readonly InputAction m_Player_Deselect;
    private readonly InputAction m_Player_Select;
    private readonly InputAction m_Player_SwapPlayerHands;
    public struct PlayerActions
    {
        private @PlayerControls m_Wrapper;
        public PlayerActions(@PlayerControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @NavCardLeft => m_Wrapper.m_Player_NavCardLeft;
        public InputAction @NavCardRight => m_Wrapper.m_Player_NavCardRight;
        public InputAction @NavigateFingerUp => m_Wrapper.m_Player_NavigateFingerUp;
        public InputAction @NavigateFingerDown => m_Wrapper.m_Player_NavigateFingerDown;
        public InputAction @NavigateFingerLeft => m_Wrapper.m_Player_NavigateFingerLeft;
        public InputAction @NavigateFingerRight => m_Wrapper.m_Player_NavigateFingerRight;
        public InputAction @SeePlayerHealth => m_Wrapper.m_Player_SeePlayerHealth;
        public InputAction @SeeEnemyHealth => m_Wrapper.m_Player_SeeEnemyHealth;
        public InputAction @SeePlayerMana => m_Wrapper.m_Player_SeePlayerMana;
        public InputAction @SeeEnemyMana => m_Wrapper.m_Player_SeeEnemyMana;
        public InputAction @Pause => m_Wrapper.m_Player_Pause;
        public InputAction @Deselect => m_Wrapper.m_Player_Deselect;
        public InputAction @Select => m_Wrapper.m_Player_Select;
        public InputAction @SwapPlayerHands => m_Wrapper.m_Player_SwapPlayerHands;
        public InputActionMap Get() { return m_Wrapper.m_Player; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerActions set) { return set.Get(); }
        public void AddCallbacks(IPlayerActions instance)
        {
            if (instance == null || m_Wrapper.m_PlayerActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PlayerActionsCallbackInterfaces.Add(instance);
            @NavCardLeft.started += instance.OnNavCardLeft;
            @NavCardLeft.performed += instance.OnNavCardLeft;
            @NavCardLeft.canceled += instance.OnNavCardLeft;
            @NavCardRight.started += instance.OnNavCardRight;
            @NavCardRight.performed += instance.OnNavCardRight;
            @NavCardRight.canceled += instance.OnNavCardRight;
            @NavigateFingerUp.started += instance.OnNavigateFingerUp;
            @NavigateFingerUp.performed += instance.OnNavigateFingerUp;
            @NavigateFingerUp.canceled += instance.OnNavigateFingerUp;
            @NavigateFingerDown.started += instance.OnNavigateFingerDown;
            @NavigateFingerDown.performed += instance.OnNavigateFingerDown;
            @NavigateFingerDown.canceled += instance.OnNavigateFingerDown;
            @NavigateFingerLeft.started += instance.OnNavigateFingerLeft;
            @NavigateFingerLeft.performed += instance.OnNavigateFingerLeft;
            @NavigateFingerLeft.canceled += instance.OnNavigateFingerLeft;
            @NavigateFingerRight.started += instance.OnNavigateFingerRight;
            @NavigateFingerRight.performed += instance.OnNavigateFingerRight;
            @NavigateFingerRight.canceled += instance.OnNavigateFingerRight;
            @SeePlayerHealth.started += instance.OnSeePlayerHealth;
            @SeePlayerHealth.performed += instance.OnSeePlayerHealth;
            @SeePlayerHealth.canceled += instance.OnSeePlayerHealth;
            @SeeEnemyHealth.started += instance.OnSeeEnemyHealth;
            @SeeEnemyHealth.performed += instance.OnSeeEnemyHealth;
            @SeeEnemyHealth.canceled += instance.OnSeeEnemyHealth;
            @SeePlayerMana.started += instance.OnSeePlayerMana;
            @SeePlayerMana.performed += instance.OnSeePlayerMana;
            @SeePlayerMana.canceled += instance.OnSeePlayerMana;
            @SeeEnemyMana.started += instance.OnSeeEnemyMana;
            @SeeEnemyMana.performed += instance.OnSeeEnemyMana;
            @SeeEnemyMana.canceled += instance.OnSeeEnemyMana;
            @Pause.started += instance.OnPause;
            @Pause.performed += instance.OnPause;
            @Pause.canceled += instance.OnPause;
            @Deselect.started += instance.OnDeselect;
            @Deselect.performed += instance.OnDeselect;
            @Deselect.canceled += instance.OnDeselect;
            @Select.started += instance.OnSelect;
            @Select.performed += instance.OnSelect;
            @Select.canceled += instance.OnSelect;
            @SwapPlayerHands.started += instance.OnSwapPlayerHands;
            @SwapPlayerHands.performed += instance.OnSwapPlayerHands;
            @SwapPlayerHands.canceled += instance.OnSwapPlayerHands;
        }

        private void UnregisterCallbacks(IPlayerActions instance)
        {
            @NavCardLeft.started -= instance.OnNavCardLeft;
            @NavCardLeft.performed -= instance.OnNavCardLeft;
            @NavCardLeft.canceled -= instance.OnNavCardLeft;
            @NavCardRight.started -= instance.OnNavCardRight;
            @NavCardRight.performed -= instance.OnNavCardRight;
            @NavCardRight.canceled -= instance.OnNavCardRight;
            @NavigateFingerUp.started -= instance.OnNavigateFingerUp;
            @NavigateFingerUp.performed -= instance.OnNavigateFingerUp;
            @NavigateFingerUp.canceled -= instance.OnNavigateFingerUp;
            @NavigateFingerDown.started -= instance.OnNavigateFingerDown;
            @NavigateFingerDown.performed -= instance.OnNavigateFingerDown;
            @NavigateFingerDown.canceled -= instance.OnNavigateFingerDown;
            @NavigateFingerLeft.started -= instance.OnNavigateFingerLeft;
            @NavigateFingerLeft.performed -= instance.OnNavigateFingerLeft;
            @NavigateFingerLeft.canceled -= instance.OnNavigateFingerLeft;
            @NavigateFingerRight.started -= instance.OnNavigateFingerRight;
            @NavigateFingerRight.performed -= instance.OnNavigateFingerRight;
            @NavigateFingerRight.canceled -= instance.OnNavigateFingerRight;
            @SeePlayerHealth.started -= instance.OnSeePlayerHealth;
            @SeePlayerHealth.performed -= instance.OnSeePlayerHealth;
            @SeePlayerHealth.canceled -= instance.OnSeePlayerHealth;
            @SeeEnemyHealth.started -= instance.OnSeeEnemyHealth;
            @SeeEnemyHealth.performed -= instance.OnSeeEnemyHealth;
            @SeeEnemyHealth.canceled -= instance.OnSeeEnemyHealth;
            @SeePlayerMana.started -= instance.OnSeePlayerMana;
            @SeePlayerMana.performed -= instance.OnSeePlayerMana;
            @SeePlayerMana.canceled -= instance.OnSeePlayerMana;
            @SeeEnemyMana.started -= instance.OnSeeEnemyMana;
            @SeeEnemyMana.performed -= instance.OnSeeEnemyMana;
            @SeeEnemyMana.canceled -= instance.OnSeeEnemyMana;
            @Pause.started -= instance.OnPause;
            @Pause.performed -= instance.OnPause;
            @Pause.canceled -= instance.OnPause;
            @Deselect.started -= instance.OnDeselect;
            @Deselect.performed -= instance.OnDeselect;
            @Deselect.canceled -= instance.OnDeselect;
            @Select.started -= instance.OnSelect;
            @Select.performed -= instance.OnSelect;
            @Select.canceled -= instance.OnSelect;
            @SwapPlayerHands.started -= instance.OnSwapPlayerHands;
            @SwapPlayerHands.performed -= instance.OnSwapPlayerHands;
            @SwapPlayerHands.canceled -= instance.OnSwapPlayerHands;
        }

        public void RemoveCallbacks(IPlayerActions instance)
        {
            if (m_Wrapper.m_PlayerActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPlayerActions instance)
        {
            foreach (var item in m_Wrapper.m_PlayerActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PlayerActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public PlayerActions @Player => new PlayerActions(this);

    // UI
    private readonly InputActionMap m_UI;
    private List<IUIActions> m_UIActionsCallbackInterfaces = new List<IUIActions>();
    private readonly InputAction m_UI_UI_Move;
    private readonly InputAction m_UI_UI_Select;
    public struct UIActions
    {
        private @PlayerControls m_Wrapper;
        public UIActions(@PlayerControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @UI_Move => m_Wrapper.m_UI_UI_Move;
        public InputAction @UI_Select => m_Wrapper.m_UI_UI_Select;
        public InputActionMap Get() { return m_Wrapper.m_UI; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(UIActions set) { return set.Get(); }
        public void AddCallbacks(IUIActions instance)
        {
            if (instance == null || m_Wrapper.m_UIActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_UIActionsCallbackInterfaces.Add(instance);
            @UI_Move.started += instance.OnUI_Move;
            @UI_Move.performed += instance.OnUI_Move;
            @UI_Move.canceled += instance.OnUI_Move;
            @UI_Select.started += instance.OnUI_Select;
            @UI_Select.performed += instance.OnUI_Select;
            @UI_Select.canceled += instance.OnUI_Select;
        }

        private void UnregisterCallbacks(IUIActions instance)
        {
            @UI_Move.started -= instance.OnUI_Move;
            @UI_Move.performed -= instance.OnUI_Move;
            @UI_Move.canceled -= instance.OnUI_Move;
            @UI_Select.started -= instance.OnUI_Select;
            @UI_Select.performed -= instance.OnUI_Select;
            @UI_Select.canceled -= instance.OnUI_Select;
        }

        public void RemoveCallbacks(IUIActions instance)
        {
            if (m_Wrapper.m_UIActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IUIActions instance)
        {
            foreach (var item in m_Wrapper.m_UIActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_UIActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public UIActions @UI => new UIActions(this);
    private int m_KeyboardMouseSchemeIndex = -1;
    public InputControlScheme KeyboardMouseScheme
    {
        get
        {
            if (m_KeyboardMouseSchemeIndex == -1) m_KeyboardMouseSchemeIndex = asset.FindControlSchemeIndex("Keyboard&Mouse");
            return asset.controlSchemes[m_KeyboardMouseSchemeIndex];
        }
    }
    private int m_GamepadSchemeIndex = -1;
    public InputControlScheme GamepadScheme
    {
        get
        {
            if (m_GamepadSchemeIndex == -1) m_GamepadSchemeIndex = asset.FindControlSchemeIndex("Gamepad");
            return asset.controlSchemes[m_GamepadSchemeIndex];
        }
    }
    private int m_TouchSchemeIndex = -1;
    public InputControlScheme TouchScheme
    {
        get
        {
            if (m_TouchSchemeIndex == -1) m_TouchSchemeIndex = asset.FindControlSchemeIndex("Touch");
            return asset.controlSchemes[m_TouchSchemeIndex];
        }
    }
    private int m_JoystickSchemeIndex = -1;
    public InputControlScheme JoystickScheme
    {
        get
        {
            if (m_JoystickSchemeIndex == -1) m_JoystickSchemeIndex = asset.FindControlSchemeIndex("Joystick");
            return asset.controlSchemes[m_JoystickSchemeIndex];
        }
    }
    private int m_XRSchemeIndex = -1;
    public InputControlScheme XRScheme
    {
        get
        {
            if (m_XRSchemeIndex == -1) m_XRSchemeIndex = asset.FindControlSchemeIndex("XR");
            return asset.controlSchemes[m_XRSchemeIndex];
        }
    }
    public interface IPlayerActions
    {
        void OnNavCardLeft(InputAction.CallbackContext context);
        void OnNavCardRight(InputAction.CallbackContext context);
        void OnNavigateFingerUp(InputAction.CallbackContext context);
        void OnNavigateFingerDown(InputAction.CallbackContext context);
        void OnNavigateFingerLeft(InputAction.CallbackContext context);
        void OnNavigateFingerRight(InputAction.CallbackContext context);
        void OnSeePlayerHealth(InputAction.CallbackContext context);
        void OnSeeEnemyHealth(InputAction.CallbackContext context);
        void OnSeePlayerMana(InputAction.CallbackContext context);
        void OnSeeEnemyMana(InputAction.CallbackContext context);
        void OnPause(InputAction.CallbackContext context);
        void OnDeselect(InputAction.CallbackContext context);
        void OnSelect(InputAction.CallbackContext context);
        void OnSwapPlayerHands(InputAction.CallbackContext context);
    }
    public interface IUIActions
    {
        void OnUI_Move(InputAction.CallbackContext context);
        void OnUI_Select(InputAction.CallbackContext context);
    }
}
